### ISSUE TITLE
你们没有用网易云的接口，是吗？

### ISSUE THREAD

**Issue by ssttii** [HENUTeam/NetEasyMusic#18]
---
我看这下边t3.henu.left_library.GYB_solve.Activities.SongInfo;

**Comment by henugyb** [comment]
没有   是根据网页版网易云请求的url得到的

**Comment by ssttii** [comment]
奥，当时我没仔细看，你们这个NetWork/MusicNetWork.java调用的api现在还能用吗

**Comment by henugyb** [comment]
现在好像不能播放了，网易云给限制了，不过百度音乐的还可以用，

**Comment by henugyb** [comment]
除了不能播放其他的都好好的

**Comment by henugyb** [comment]
网易云没有官方的接口
